#    ,.       .  .   .-,--. .
#   / |   . . |- |-.  '|__/ |  . . ,-. . ,-.
#  /~~|-. | | |  | |  .|    |  | | | | | | |
#,'   `-' `-' `' ' '  `'    `' `-' `-| ' ' '
#                                   ,|
#                                   `'
#by laptoff,

########################################################################################################################
#                                                       Database                                                       #
#                                                                                                                      #
#This section is to set database parameters.                                                                           #
#You can disable/enable the database system by setting "enable" to "true" or "false".                                  #
#Please, if you can, follow our recommendations.                                                                       #
#                                                                                                                      #
#We recommend, for you:                                                                                                #
# - Use a password for the user which have access at your database.                                                    #
# - Don't use the root user.                                                                                           #
#                                                                                                                      #
#Notes: We prefer mariadb. This is the driver will be prioritized over the others.                                     #
#To modify a setting, you need to stop your server. Otherwise, AuthPlugin will be disconnected from the database.      #
########################################################################################################################


database:
  enable: false

  #Motor is the system which is used by your database. For now, only "mysql" (for mysql) and "mariadb" (for mariadb) can be used.
  motor: mariadb

  #You must to setting the ip address of the server which host your database. If your database run on locale, you can set to "localht" or "127.0.0.1".
  host: 127.0.0.1

  #You must set the port of your server. The default port for mysql or mariadb is 3306.
  port: 3306

  #The name of your database. It's an obligation.
  database_name: authplugin_database

  #You need to set the user which will all access to the database. Please read the recommended section !
  user: root

  #The password of the user. Please read the recommendation section !
  password: ineedcoffee974



messages:

  #Startings messages
  starting:
    onStart: "The authentication system started !"
    onDisable: "The authentication system is disabled !"

  #Databases messages
  database:
    success_connection: "Authenticator connected to database !"
    success_disconnection: "Authenticator disconnected to database !"

  #Authenticator Messages
  authenticator:
    create_account: <gold>You must create your account ! (/account new [identifier], [password])
    connect_to_account: <yellow> You must to connect at your account ! (/account connect [password])
    success_creation: <green>Good Game! You created your account! <yellow> Connect to your account now! (/account connect [password])
    success_connection: <green> Good Game! You are now connected !
    success_forgot: <green> Your account is now deleted ! Please reconnect yourself !


  # %s = Bot Verification code.
  anti-bot:
    bot_verification: "<red> You need to pass the bot verification test, please send: <gold> %s"
    bot_verification_failed: "<red> This is not the good captcha... Please retry with: <gold> %s"
    bot_verification_succeed: "<green> You successfully passed the bot verification !"


  errors:
    wrong_number_of_arguments: <red>Your command has a wrong number of arguments !

    #authenticator
    already_an_account: <red> You have already an account !
    already_connected: <red> You are already connected !
    has_not_account: <red> You must to create an account !
    incorrect_password: <red> This is the wrong password :(
    incorrect_identifier: <red> This is the wrong identifier :(
    incorrect_entity: <red> You need to be a player to perform this command !
