#    ,.       .  .   .-,--. .
#   / |   . . |- |-.  '|__/ |  . . ,-. . ,-.
#  /~~|-. | | |  | |  .|    |  | | | | | | |
#,'   `-' `-' `' ' '  `'    `' `-' `-| ' ' '
#                                   ,|
#                                   `'
#by laptoff,

name: AuthPlugin
version: '${project.version}'
author: laptoff
load: STARTUP
contributors: [laptoff]
main: fr.laptoff.authplugin.AuthPlugin

commands:
  account:
    description: allows accounts managing.
    aliases: [ac]